/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Cliente;
import ar.com.gmeventas.entities.IvaCompras;
import ar.com.gmeventas.main.MainFrame;
import ar.com.gmeventas.services.IvaComprasServices;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class AbmIvaComprasFrame extends javax.swing.JFrame {
    private List<IvaCompras> ivaComprasLista = null;
    private int selectRow;
    private Date filtroPeriodo;
    private IvaCompras ivaCompra;
    

    /**
     * Creates new form AbmIvaCompras
     */
    public AbmIvaComprasFrame() {
        initComponents();
        limpiarCampos();
        llenarCombos();
//        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ivaCompras = new javax.swing.JScrollPane();
        ivaComprasTabla = new javax.swing.JTable();
        nuevoBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        borrarBtn = new javax.swing.JButton();
        comboMes = new javax.swing.JComboBox();
        comboAnio = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ivaComprasTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Proveedor", "Fecha Factura", "Factura", "Importe"
            }
        ));
        ivaCompras.setViewportView(ivaComprasTabla);
        if (ivaComprasTabla.getColumnModel().getColumnCount() > 0) {
            ivaComprasTabla.getColumnModel().getColumn(0).setResizable(false);
            ivaComprasTabla.getColumnModel().getColumn(0).setPreferredWidth(100);
            ivaComprasTabla.getColumnModel().getColumn(1).setPreferredWidth(200);
            ivaComprasTabla.getColumnModel().getColumn(2).setResizable(false);
            ivaComprasTabla.getColumnModel().getColumn(2).setPreferredWidth(100);
            ivaComprasTabla.getColumnModel().getColumn(3).setResizable(false);
            ivaComprasTabla.getColumnModel().getColumn(3).setPreferredWidth(100);
            ivaComprasTabla.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Volver");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Periodo:");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        borrarBtn.setText("Borrar");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        archivo.setText("Archivo");
        jMenuBar1.add(archivo);

        salir.setText("Volver");
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ivaCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoBtn)
                        .addGap(81, 81, 81)
                        .addComponent(modificarBtn)
                        .addGap(94, 94, 94)
                        .addComponent(borrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atrasBtn)
                        .addGap(33, 33, 33))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buscarBtn)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarBtn)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(ivaCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoBtn)
                    .addComponent(modificarBtn)
                    .addComponent(borrarBtn)
                    .addComponent(atrasBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        NuevoIvaComprasFrame niv = new NuevoIvaComprasFrame();
        niv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        modificar();
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        buscarPeriodo();
    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbmIvaComprasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbmIvaComprasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbmIvaComprasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbmIvaComprasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbmIvaComprasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JButton borrarBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JComboBox comboAnio;
    private javax.swing.JComboBox comboMes;
    private javax.swing.JScrollPane ivaCompras;
    private javax.swing.JTable ivaComprasTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
//        if (!periodoBuscarTxt.getText().isEmpty()){
//        try{
//            ivaComprasLista = new ArrayList<>();
//            ivaComprasLista = new IvaComprasServices().getAllIvaCompras();
//        }
//        catch(Exception ex){
//            JOptionPane.showMessageDialog(this, "Iva Compras - Error, no se puede llenar la tabla");
//        }
        DefaultTableModel defaultTableModel = (DefaultTableModel) ivaComprasTabla.getModel();
//        DefaultTableModel defaultTableModel = new DefaultTableModel();
//        defaultTableModel.addColumn("Orden");
//        defaultTableModel.addColumn("Proveedor");
//        defaultTableModel.addColumn("Fecha Factura");
//        defaultTableModel.addColumn("Numero");
//        defaultTableModel.addColumn("Total");
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if(ivaComprasLista != null && !ivaComprasLista.isEmpty()){
            for(IvaCompras ic: ivaComprasLista){
                Object[] fila = new Object[5];
                fila[0] = ic.getId();
                fila[1] = ic.getProveedor().getRazonSocial();
                fila[2] = sdf.format(ic.getFechaFactura());
                fila[3] = ic.getNumeroFactura();
                fila[4] = ic.getTotal();
                defaultTableModel.addRow(fila);
            }    
//        }
        ivaComprasTabla.setModel(defaultTableModel);
        }
    }

    private void modificar() {
        ivaCompra = null;
        selectRow = ivaComprasTabla.getSelectedRow();
        if (selectRow >-1){
            System.out.println(selectRow);
            ivaCompra = this.getIvaComprasSeleccionado();
            if (ivaCompra != null) {
                ModificarIvaComprasFrame micf = new ModificarIvaComprasFrame(ivaCompra);
                micf.setVisible(true);
                this.dispose();
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una factura para modificar");
        }
    }

    private void limpiarCampos() {
//        periodoBuscarTxt.setText("");
    }

    private void buscarPeriodo() {
        if (comboMes.getSelectedIndex() > 0){
            if (comboAnio.getSelectedIndex() > 0){
                int mes = comboMes.getSelectedIndex();
//                String aniox = (String) ;
                Integer anio = (Integer) comboAnio.getSelectedItem();
                
                try {
                    List<IvaCompras> ic = new IvaComprasServices().getIvaComprasByFiltro(mes, anio);
                    if (ic.isEmpty()) {
                        JOptionPane.showMessageDialog(this,"No hay registros para esta fecha");
                    }
                    ivaComprasLista = ic;
                } catch (Exception ex) {
                    Logger.getLogger(AbmIvaComprasFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
                JOptionPane.showMessageDialog(this,"DEBE SELECCIONAR UN AÑO");
            }
        }else{
            JOptionPane.showMessageDialog(this,"DEBE SELECCIONAR UN MES");
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        llenarTabla();
//        try {
//            filtroPeriodo = sdf.parse(periodoBuscarTxt.getText());
//            
//        } catch (ParseException ex) {
//            Logger.getLogger(AbmIvaComprasFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void llenarCombos() {
        Date date = new Date();
        int anio = date.getYear() + 1900;
        int desdeAnio = 2013;
        comboAnio.removeAllItems();
        comboAnio.addItem("");
        for (int x = desdeAnio; x <= anio; x++){
            comboAnio.addItem(x);
        }
        comboMes.removeAllItems();
        comboMes.addItem("");
        comboMes.addItem("ENERO");
        comboMes.addItem("FEBRERO");
        comboMes.addItem("MARZO");
        comboMes.addItem("ABRIL");
        comboMes.addItem("MAYO");
        comboMes.addItem("JUNIO");
        comboMes.addItem("JULIO");
        comboMes.addItem("AGOSTO");
        comboMes.addItem("SETIEMBRE");
        comboMes.addItem("OCTUBRE");
        comboMes.addItem("NOVIEMBRE");
        comboMes.addItem("DICIEMBRE");
    }

    private IvaCompras getIvaComprasSeleccionado() {
        
        int filaSeleccionada = ivaComprasTabla.getSelectedRow();
        
        if(filaSeleccionada != -1){
            IvaCompras ivaCompras = ivaComprasLista.get(filaSeleccionada);
            return ivaCompras;
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Factura de la lista.");
        }        
        return null;
        
    }
}
