/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.SubRubro;
import ar.com.gmeventas.main.MainFrame;
import ar.com.gmeventas.services.SubRubroService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class AbmSubRubroFrame extends javax.swing.JFrame {
    List<SubRubro> listaSubRubro = new ArrayList();
    /**
     * Creates new form AbmSubRubroFrame
     */
    public AbmSubRubroFrame() {
        initComponents();
        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        subRubroTabla = new javax.swing.JTable();
        nuevoBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        borrarBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        nuevoMenuBtn = new javax.swing.JMenuItem();
        modificarMenuBtn = new javax.swing.JMenuItem();
        eliminarMenuBtn = new javax.swing.JMenuItem();
        volverMenuBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        subRubroTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(subRubroTabla);

        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        borrarBtn.setText("Borrar");
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });

        archivoMenu.setText("Archivo");

        nuevoMenuBtn.setText("nuevo");
        archivoMenu.add(nuevoMenuBtn);

        modificarMenuBtn.setText("modificar");
        archivoMenu.add(modificarMenuBtn);

        eliminarMenuBtn.setText("eliminar");
        archivoMenu.add(eliminarMenuBtn);

        jMenuBar1.add(archivoMenu);

        volverMenuBtn.setText("Volver");
        volverMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuBtnActionPerformed(evt);
            }
        });
        jMenuBar1.add(volverMenuBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nuevoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(borrarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(volverBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(nuevoBtn)
                    .addComponent(modificarBtn)
                    .addComponent(borrarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void volverMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuBtnActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        SubRubro subRubro = this.getSubRubroSeleccionado();
        ModificarSubRubroFrame msr = new ModificarSubRubroFrame(subRubro);
        msr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        NuevoSubRubroFrame nsrf = new NuevoSubRubroFrame();
        nsrf.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        this.borrarSubrubroSeleccionado();
    }//GEN-LAST:event_borrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbmSubRubroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbmSubRubroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbmSubRubroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbmSubRubroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbmSubRubroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JButton borrarBtn;
    private javax.swing.JMenuItem eliminarMenuBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JMenuItem modificarMenuBtn;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JMenuItem nuevoMenuBtn;
    private javax.swing.JTable subRubroTabla;
    private javax.swing.JButton volverBtn;
    private javax.swing.JMenu volverMenuBtn;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
        
        try{
            SubRubroService subRubroService = new SubRubroService();
            listaSubRubro = subRubroService.getAllSubRubros();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "error en la base de datos");
        }
       DefaultTableModel model = new DefaultTableModel();
       model.addColumn("CODIGO");
       model.addColumn("DETALLE");
       if(listaSubRubro!=null && !listaSubRubro.isEmpty()){
           for (SubRubro subRubro : listaSubRubro ){
               
               Object[] fila = new Object[2];
               fila[0] = subRubro.getCodigo();
               fila[1] = subRubro.getDetalle();
               model.addRow(fila);
           }
           subRubroTabla.setModel(model);
       }
    }

    private SubRubro getSubRubroSeleccionado() {
        SubRubro subRubro = null;
        int filaSeleccionada = subRubroTabla.getSelectedRow();
        
        if(filaSeleccionada != -1 && listaSubRubro != null && !listaSubRubro.isEmpty()){
        subRubro = listaSubRubro.get(filaSeleccionada);
        }
        else{
        JOptionPane.showMessageDialog(this , "SubRubro - Seleccione un item de la lista");
        }
        return subRubro;
    }

    private void borrarSubrubroSeleccionado() {
        int filaSeleccionada = subRubroTabla.getSelectedRow();
        if(filaSeleccionada != -1){
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Desea eliminar al Sub Rubro?",
                    "Borrar - Sub Rubro",
                    JOptionPane.OK_OPTION);
            if(confirm == JOptionPane.OK_OPTION){
            SubRubro subRubroABorrar = getSubRubroSeleccionado();
            try{
                new SubRubroService().deleteSubRubro(subRubroABorrar);
                subRubroTabla.removeAll();
                this.llenarTabla();
            }
            
            catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Sub Rubro - Seleccione un sub Rubro de la lista");
            }
            
            
            }
        }
    }

 }