/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Cliente;
import ar.com.gmeventas.entities.IvaVentas;
import ar.com.gmeventas.main.MainFrame;
import ar.com.gmeventas.services.ClienteService;
import ar.com.gmeventas.services.IvaVentasService;
import ar.com.gmeventas.util.LectorDeExcel;
import java.io.File;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;

/**
 *
 * @author Marcela
 */
public class ImportarLibroIvaFrame extends javax.swing.JFrame {

    private File archivoImportado = null;
    private List<IvaVentas> iva = null;
    private DecimalFormat df = new DecimalFormat("#0.00");

    /**
     * Creates new form ImporterClienteFrame
     */
    public ImportarLibroIvaFrame(File archivo) {
        initComponents();
        this.archivoImportado = archivo;
        try {
            this.llenarTablaLibroIvaImportado();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error importando los datos.\nSi esto persiste, asegurese que el archivo sea correcto.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIvaImportado = new javax.swing.JTable();
        aceptarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaIvaImportado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Letra", "Sucu", "Núm", "Fecha", "Cuit", "Cliente", "CAE", "Venc.Cae", "Total", "Impuesto", "Gravado", "Iva"
            }
        ));
        jScrollPane1.setViewportView(tablaIvaImportado);
        if (tablaIvaImportado.getColumnModel().getColumnCount() > 0) {
            tablaIvaImportado.getColumnModel().getColumn(0).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaIvaImportado.getColumnModel().getColumn(1).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(1).setPreferredWidth(20);
            tablaIvaImportado.getColumnModel().getColumn(2).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaIvaImportado.getColumnModel().getColumn(3).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(3).setPreferredWidth(50);
            tablaIvaImportado.getColumnModel().getColumn(4).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(4).setPreferredWidth(70);
            tablaIvaImportado.getColumnModel().getColumn(5).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(5).setPreferredWidth(100);
            tablaIvaImportado.getColumnModel().getColumn(6).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(6).setPreferredWidth(60);
            tablaIvaImportado.getColumnModel().getColumn(7).setPreferredWidth(60);
            tablaIvaImportado.getColumnModel().getColumn(8).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(8).setPreferredWidth(50);
            tablaIvaImportado.getColumnModel().getColumn(9).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(9).setPreferredWidth(50);
            tablaIvaImportado.getColumnModel().getColumn(10).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(10).setPreferredWidth(50);
            tablaIvaImportado.getColumnModel().getColumn(11).setResizable(false);
            tablaIvaImportado.getColumnModel().getColumn(11).setPreferredWidth(50);
        }

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(aceptarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBtn)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(volverBtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        guardarLibroIva();
    }//GEN-LAST:event_aceptarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportarLibroIvaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportarLibroIvaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportarLibroIvaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportarLibroIvaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportarLibroIvaFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaIvaImportado;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaLibroIvaImportado() {

        try {
            iva = LectorDeExcel.importarIvaVentas(archivoImportado);
        } catch (BiffException ex) {
            Logger.getLogger(ImportarLibroIvaFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ImportarLibroIvaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelo = (DefaultTableModel) tablaIvaImportado.getModel();
        if (iva != null && !iva.isEmpty()) {
            for (IvaVentas row : iva) {
                Object[] fila = new Object[12];
                fila[0] = row.getLetra();
                fila[1] = row.getNumeroSucursal();
                fila[2] = row.getNumeroFactura();
                fila[3] = row.getFecha();
                fila[4] = row.getCliente().getCuit();
                fila[5] = row.getCliente().getRazonSocial();
                fila[6] = row.getCae();
                fila[7] = row.getFechaCae();
                fila[8] = df.format(row.getTotal());
                fila[9] = df.format(row.getImpuesto());
                fila[10] = df.format(row.getGravado());
                fila[11] = df.format(row.getIva());
                modelo.addRow(fila);
            }
            tablaIvaImportado.setModel(modelo);
        } else {
            Object[] mensaje = new Object[1];
            mensaje[1] = "No se recuperó ningún dato de Iva del archivo importado";
            modelo.addRow(mensaje);
        }

    }

    private void guardarLibroIva() {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Se guardarán todos las Facturas listadas.\n¿Confirma la operación?",
                "Confirmar", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == JOptionPane.OK_OPTION) {
            try {
                new IvaVentasService().saveListaFacturas(iva);
                JOptionPane.showMessageDialog(this, "Facturas guardadas correctamente.");
                MainFrame mf = new MainFrame();
                mf.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }
}
