/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Producto;
import ar.com.gmeventas.main.MainFrame;
import ar.com.gmeventas.services.ProductoService;
import ar.com.gmeventas.util.LectorDeExcel;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;


/**
 *
 * @author Marcela
 */
public class ImportarProductoFrame extends javax.swing.JFrame {
    
    private File archivoImportado = null;
    private List<Producto> listaProductos = null;

    /**
     * Creates new form ImportarProducto
     */
    public ImportarProductoFrame(File archivo) {
        initComponents();
        this.archivoImportado = archivo;
        try{
            this.llenarTablaProductoImportado();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error importando los datos.\nSi esto persiste, asegurese que el archivo sea correcto.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductoImportado = new javax.swing.JTable();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProductoImportado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "DESCRIPCION", "PRECIO", "IMPUESTO", "SUGERIDO", "RUBRO", "SUBRUBRO"
            }
        ));
        jScrollPane1.setViewportView(tablaProductoImportado);
        if (tablaProductoImportado.getColumnModel().getColumnCount() > 0) {
            tablaProductoImportado.getColumnModel().getColumn(0).setResizable(false);
            tablaProductoImportado.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablaProductoImportado.getColumnModel().getColumn(1).setPreferredWidth(300);
            tablaProductoImportado.getColumnModel().getColumn(2).setPreferredWidth(40);
            tablaProductoImportado.getColumnModel().getColumn(3).setPreferredWidth(40);
            tablaProductoImportado.getColumnModel().getColumn(4).setPreferredWidth(40);
            tablaProductoImportado.getColumnModel().getColumn(5).setPreferredWidth(40);
            tablaProductoImportado.getColumnModel().getColumn(6).setPreferredWidth(40);
        }

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(aceptarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarBtn)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        guardarProductos();
    }//GEN-LAST:event_aceptarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportarProductoFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductoImportado;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaProductoImportado() throws IOException, BiffException, Exception {
        listaProductos = LectorDeExcel.leerExcelProducto(archivoImportado);
        DefaultTableModel modelo = (DefaultTableModel) tablaProductoImportado.getModel();
        if(listaProductos != null && !listaProductos.isEmpty()){
            for(Producto produ : listaProductos){
                Object[] fila = new Object[7];
                
                fila[0] = produ.getCodigo();
                fila[1] = produ.getDetalle();
                fila[2] = produ.getPrecio();
                fila[3] = produ.getImpuesto();
                fila[4] = produ.getSugerido();
                fila[5] = produ.getRubro().getCodigo();
                fila[6] = produ.getSubRubro().getCodigo();
                modelo.addRow(fila);
            }
            tablaProductoImportado.setModel(modelo);            
        }else{
            Object[] mensaje = new Object[2];
            mensaje[0] = " ";
            mensaje[1] = "No se recuperó ningún PRODUCTO del archivo";
            modelo.addRow(mensaje);
            aceptarBtn.setEnabled(false);
        }
    }

    private void guardarProductos() {
        int confirm = JOptionPane.showConfirmDialog(this, "Se guardarán todos los PRODUCTOS listados.\n¿Confirma la operación?",
            "Confirmar", JOptionPane.OK_CANCEL_OPTION);
        if(confirm == JOptionPane.OK_OPTION){
            try{
                new ProductoService().saveListaProductos(listaProductos);
                JOptionPane.showMessageDialog(this, "Productos guardados correctamente.");
                MainFrame mf = new MainFrame();
                mf.setVisible(true);
                this.dispose();
            }catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
