/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.CodigoBarras;
import ar.com.gmeventas.entities.Producto;
import ar.com.gmeventas.main.MainFrame;
import ar.com.gmeventas.services.CodigosBarraService;
import ar.com.gmeventas.services.ProductoService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class IngresarCodigosBarraFrame extends javax.swing.JFrame {

    List<Producto> productos;

    /**
     * Creates new form IngresarCodigosBarraFrame
     */
    public IngresarCodigosBarraFrame() {
        initComponents();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoBarrasTxt = new javax.swing.JTextField();
        filtroTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        listarCodAndProdBtn = new javax.swing.JButton();
        nuevoProductoBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        codigoTestTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoProductoTxt = new javax.swing.JTextField();
        detalleTxt = new javax.swing.JTextField();
        productosSinCodBtn = new javax.swing.JButton();
        eliminatBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INGRESAR CODIGOS BARRA PRODUCTOS");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Código de Barra:");

        jLabel2.setText("Nombre Producto:");

        codigoBarrasTxt.setText("CODIGO BARRAS");
        codigoBarrasTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoBarrasTxtKeyPressed(evt);
            }
        });

        filtroTxt.setText("FILTRO");
        filtroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroTxtKeyPressed(evt);
            }
        });

        jLabel3.setText("Seleccione Producto:");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });

        listarCodAndProdBtn.setText("Listar Codigos y Productos");
        listarCodAndProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCodAndProdBtnActionPerformed(evt);
            }
        });

        nuevoProductoBtn.setText("Nuevo Producto");
        nuevoProductoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProductoBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese Código Barras:");

        codigoTestTxt.setText("CODIGO BARRAS TEST");
        codigoTestTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTestTxtKeyPressed(evt);
            }
        });

        jLabel5.setText("Código Producto:");

        jLabel6.setText("Descripción:");

        codigoProductoTxt.setText("CODIGO");

        detalleTxt.setText("DETALLE");

        productosSinCodBtn.setText("ListarProductos sin Código");
        productosSinCodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosSinCodBtnActionPerformed(evt);
            }
        });

        eliminatBtn.setText("Eliminar Código Barras");
        eliminatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(nuevoProductoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detalleTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codigoProductoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminatBtn))
                                    .addComponent(codigoTestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listarCodAndProdBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(productosSinCodBtn, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoProductoBtn)
                    .addComponent(volverBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codigoTestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarCodAndProdBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codigoProductoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productosSinCodBtn)
                    .addComponent(eliminatBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(detalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void filtroTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!filtroTxt.getText().isEmpty()) {
                codigoProductoTxt.setText("");
                detalleTxt.setText("");
                llenarCombo();
            }
        }
    }//GEN-LAST:event_filtroTxtKeyPressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        if (evt.getModifiers() == 16) {
            int row = combo.getSelectedIndex();
            if (row > 0) {
                codigoBarrasTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_comboActionPerformed

    private void codigoBarrasTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarrasTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!codigoBarrasTxt.getText().isEmpty()) {
                Producto p = null;
                System.out.println(Long.valueOf(codigoBarrasTxt.getText()));
                try {
                    p = new ProductoService().getProductoByCodigoBarras(Long.valueOf(codigoBarrasTxt.getText()));
                } catch (Exception ex) {
                    //Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(p);
                if (p != null) {
                    JOptionPane.showMessageDialog(this, "Codigo existente");
                    return;
                }
//                else{
//                    JOptionPane.showMessageDialog(this, "Codigo disponible");
//                }
                int r = combo.getSelectedIndex();
                CodigoBarras cb = new CodigoBarras();
                cb.setCodigo(Long.valueOf(codigoBarrasTxt.getText()));
                if (r > 0) {
                    p = productos.get(r - 1);
                    cb.setProducto(p);
                    try {
                        new CodigosBarraService().save(cb);
                    } catch (Exception ex) {
                        Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    codigoBarrasTxt.setText("");
                    JOptionPane.showMessageDialog(this, "Ingresado Correctamente");
                    codigoBarrasTxt.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_codigoBarrasTxtKeyPressed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        if (evt.getKeyCode() == 10) {
            int r = combo.getSelectedIndex();
            if (r > 0) {
                codigoBarrasTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_comboKeyPressed

    private void codigoTestTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTestTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!codigoTestTxt.getText().isEmpty()) {
                buscarProducto();
            }
        }
    }//GEN-LAST:event_codigoTestTxtKeyPressed

    private void nuevoProductoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProductoBtnActionPerformed
        nuevoProducto();
    }//GEN-LAST:event_nuevoProductoBtnActionPerformed

    private void listarCodAndProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCodAndProdBtnActionPerformed
        listarCodigos();
    }//GEN-LAST:event_listarCodAndProdBtnActionPerformed

    private void productosSinCodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosSinCodBtnActionPerformed
        listarSinCodigos();
    }//GEN-LAST:event_productosSinCodBtnActionPerformed

    private void eliminatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminatBtnActionPerformed
        eliminarCodigoBarras();
    }//GEN-LAST:event_eliminatBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarCodigosBarraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoBarrasTxt;
    private javax.swing.JTextField codigoProductoTxt;
    private javax.swing.JTextField codigoTestTxt;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField detalleTxt;
    private javax.swing.JButton eliminatBtn;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listarCodAndProdBtn;
    private javax.swing.JButton nuevoProductoBtn;
    private javax.swing.JButton productosSinCodBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void limpiarCampos() {
        filtroTxt.setText("");
        combo.removeAllItems();
        combo.addItem("");
        codigoBarrasTxt.setText("");
        codigoTestTxt.setText("");
        codigoProductoTxt.setText("");
        detalleTxt.setText("");
        filtroTxt.requestFocus();
    }

    private void llenarCombo() {
        combo.removeAllItems();
        combo.addItem("");
        String filtro = filtroTxt.getText();
        productos = null;
        try {
            productos = new ProductoService().getAllProductosOrdenadoByNombre(filtro);
        } catch (Exception ex) {
            Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (productos != null && !productos.isEmpty()) {
            for (Producto p : productos) {
                combo.addItem(p.getCodigo() + " " + p.getDetalle());
            }
            combo.addFocusListener(null);
            combo.showPopup();
            combo.requestFocus();
        }
    }

    private void buscarProducto() {
        if (!codigoTestTxt.getText().isEmpty()) {
            codigoProductoTxt.setText("");
            detalleTxt.setText("");
            Producto p = null;
            Long cb = Long.valueOf(codigoTestTxt.getText());
            try {
                p = new ProductoService().getProductoByCodigoBarras(cb);
            } catch (Exception ex) {
                //Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "NO EXISTE PRODUCTO");
                codigoTestTxt.setText("");
                return;
            }
            if (p != null) {
                codigoProductoTxt.setText(p.getCodigo().toString());
                detalleTxt.setText(p.getDetalle());
                codigoTestTxt.getText();
            }
        }
    }

    private void nuevoProducto() {
        limpiarCampos();
    }

    private void listarCodigos() {
        ListarCodigosFrame lcf = new ListarCodigosFrame();
        lcf.setVisible(true);
        this.dispose();
    }

    private void listarSinCodigos() {
        ListarSinCodigosFrame lscf = new ListarSinCodigosFrame();
        lscf.setVisible(true);
        this.dispose();
    }

    private void eliminarCodigoBarras() {
        Long cod = Long.valueOf(codigoTestTxt.getText());
        int a = JOptionPane.showConfirmDialog(this, "Confirme eliminar CÓDIGO BARRAS?\n" + cod, "Atención", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            CodigoBarras cb = null;
            try {
                cb = new CodigosBarraService().getCodigoBarrasByCB(cod);
                new CodigosBarraService().delete(cb);
                JOptionPane.showMessageDialog(this, "Código de Barra ELIMINADO correctamente");
            } catch (Exception ex) {
                Logger.getLogger(IngresarCodigosBarraFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR no borrado");
            }
        }
        limpiarCampos();
    }
}