/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Producto;
import ar.com.gmeventas.entities.Rubro;
import ar.com.gmeventas.entities.SubRubro;
import ar.com.gmeventas.services.ProductoService;
import ar.com.gmeventas.services.RubroService;
import ar.com.gmeventas.services.SubRubroService;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ModificarProductoFrame extends javax.swing.JFrame {
    private final Producto producto;
    private List<Rubro> listaRubro = new ArrayList<Rubro>();
    private List<SubRubro> listaSubRubro = new ArrayList<SubRubro>();
    private String filtro = "";
    private final DecimalFormat df = new DecimalFormat("#0.000");
    /**
     * Creates new form ModificarProducto
     */
    public ModificarProductoFrame(Producto prod, String filtro) {
        initComponents();
        this.filtro = filtro;
        this.producto=prod;
        limpiarCampos();
        llenarRubros();
        llenarSubRubros();
        this.llenarCampos(prod);
        precioTxt.requestFocus();
        codigoTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JButton();
        comboSubRubro = new javax.swing.JComboBox();
        comboRubro = new javax.swing.JComboBox();
        precioTxt = new javax.swing.JTextField();
        sugeridoTxt = new javax.swing.JTextField();
        impuestoTxt = new javax.swing.JTextField();
        codigoBarrasTxt = new javax.swing.JTextField();
        codigoTxt = new javax.swing.JTextField();
        inactivoChk = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        detalleTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precioCostoTxt = new javax.swing.JTextField();
        impuestoCostoTxt = new javax.swing.JTextField();

        jLabel12.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR PRODUCTO");

        salirBtn.setText("Volver");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel4.setText("Impuesto");

        jLabel5.setText("Sugerido");

        jLabel6.setText("Precio");

        jLabel7.setText("Rubro");

        jLabel8.setText("Sub Rubro");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        comboSubRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        precioTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioTxt.setText("precio");

        sugeridoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sugeridoTxt.setText("sugerido");

        impuestoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoTxt.setText("impuesto");

        codigoBarrasTxt.setText("código barras");

        codigoTxt.setText("Codigo");

        inactivoChk.setText("inactivo");

        jLabel9.setText("Detalle:");

        detalleTxt.setText("DETALLE");

        jLabel3.setText("Código Barras:");

        jLabel10.setText("*");

        jLabel11.setText("*");

        jLabel13.setText("*");

        jLabel14.setText("*");

        jLabel15.setText("*");

        jLabel2.setText("Costos:");

        precioCostoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioCostoTxt.setText("P.COSTO");

        impuestoCostoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoCostoTxt.setText("I.COSTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirBtn)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sugeridoTxt)
                                    .addComponent(impuestoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(precioTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(impuestoCostoTxt)
                                    .addComponent(precioCostoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboRubro, 0, 264, Short.MAX_VALUE)
                                        .addComponent(comboSubRubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(detalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inactivoChk))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10))))))
                        .addGap(0, 38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inactivoChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(detalleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(precioCostoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(impuestoCostoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sugeridoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboSubRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirBtn)
                    .addComponent(guardarBtn))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        AbmProductoFrame apf = new AbmProductoFrame(filtro);
        apf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.guardarProducto();
        AbmProductoFrame apf = new AbmProductoFrame(filtro);
        apf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProductoFrame(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoBarrasTxt;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JComboBox comboRubro;
    private javax.swing.JComboBox comboSubRubro;
    private javax.swing.JTextField detalleTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField impuestoCostoTxt;
    private javax.swing.JTextField impuestoTxt;
    private javax.swing.JCheckBox inactivoChk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField precioCostoTxt;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JButton salirBtn;
    private javax.swing.JTextField sugeridoTxt;
    // End of variables declaration//GEN-END:variables

    private void llenarCampos(Producto producto) {
        codigoTxt.setText(String.valueOf(producto.getCodigo()));
        if (producto.getCodigoBarras() != null){
            codigoBarrasTxt.setText(String.valueOf(producto.getCodigoBarras()));
        }else{
            codigoBarrasTxt.setText("");
        }
        impuestoTxt.setText(df.format(producto.getImpuesto()));
        sugeridoTxt.setText(df.format(producto.getSugerido()));
        precioTxt.setText(df.format(producto.getPrecio()));
        detalleTxt.setText(producto.getDetalle());
        if(producto.getCostoP() != null){
            precioCostoTxt.setText(df.format(producto.getCostoP()));
        }else{
            precioCostoTxt.setText(df.format(0.00));
        }
        if(producto.getCostoI() != null){
            impuestoCostoTxt.setText(df.format(producto.getCostoI()));
        }else{
            impuestoCostoTxt.setText(df.format(0.00));
        }
        if (producto.getInactivo()){
            inactivoChk.setSelected(true);
        }else{
            inactivoChk.setSelected(false);
        }
        int contador = 0;
        for (Rubro rubro : listaRubro) {
            if (rubro.getId() == producto.getRubro().getId()) {
                break;
            }
            contador ++;
        }
        comboRubro.setSelectedIndex(contador+1);
        contador = 0;
        for (SubRubro sub : listaSubRubro) {
            if (sub.getId() == producto.getSubRubro().getId()) {
                break;
            }
            contador ++;
        }
        comboSubRubro.setSelectedIndex(contador+1);
    }

    private void guardarProducto() {
        if(validarCampos()){
            producto.setCodigo(Integer.valueOf(codigoTxt.getText()));
            if (!codigoBarrasTxt.getText().isEmpty()){
                producto.setCodigoBarras(Long.valueOf(codigoBarrasTxt.getText()));
            }else{
                producto.setCodigoBarras(null);
            }
            producto.setDetalle(detalleTxt.getText());
            if (!impuestoTxt.getText().isEmpty()){
                producto.setImpuesto(Float.valueOf(impuestoTxt.getText().replace(",", ".")));
            }else{
                producto.setImpuesto(Float.valueOf("0.00"));
            }
            if (!sugeridoTxt.getText().isEmpty()){
                producto.setSugerido(Double.valueOf(sugeridoTxt.getText().replace(",", ".")));
            }else{
                producto.setSugerido(Double.valueOf("0.00"));
            }
            if(precioCostoTxt.getText().isEmpty()){
                producto.setCostoP(0.00);
            }else{
                Double pc = Double.valueOf(precioCostoTxt.getText().replace(",", "."));
                producto.setCostoP(pc);
            }
            if(impuestoCostoTxt.getText().isEmpty()){
                producto.setCostoI(0.00);
            }else{
                Double ic = Double.valueOf(impuestoCostoTxt.getText().replace(",", "."));
                producto.setCostoI(ic);
            }
            producto.setPrecio(Double.valueOf(precioTxt.getText().replace(",", ".")));
            Rubro rubro = producto.getRubro();
            SubRubro sub = producto.getSubRubro();
            int indiceRubro = comboRubro.getSelectedIndex();
            RubroService RubroService = new RubroService();
            try {
                rubro = RubroService.getAllRubros().get(indiceRubro-1);
                producto.setRubro(rubro);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            int indiceSubRubro = comboSubRubro.getSelectedIndex();
            SubRubroService subRubroService = new SubRubroService();
            try {
                sub = subRubroService.getAllSubRubros().get(indiceSubRubro-1);
                producto.setSubRubro(sub);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (inactivoChk.isSelected()){
                producto.setInactivo(true);
            }else{
                producto.setInactivo(false);
            }
            try{
                new ProductoService().updateProducto(producto);
            }
            catch(Exception ex){
                java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private boolean validarCampos() {
        if (detalleTxt.getText().trim().length() > 34) {
            JOptionPane.showMessageDialog(this, "Largo Producto Superado - " + String.valueOf(detalleTxt.getText().trim().length()));
            return false;
        }
        if(codigoTxt.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Producto - Falta completar Codigo");
            return false;
        }
        if(detalleTxt.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Producto - Falta completar detalle");
            return false;
        }
        if (precioTxt.getText().trim().length()==0) {
            JOptionPane.showMessageDialog(this, "Producto - No permitido sin precio");
            return false;
        }
        if(comboRubro.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Producto - Seleccione Rubro");
            return false;
        }
        if(comboSubRubro.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "producto - Seleccione Sub Rubro");
            return false;
        }
        return true;
    }

    private void llenarRubros() {
        try{
            listaRubro = new RubroService().getAllRubros();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se encuentran Rubros para llenar");
        }
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboRubro.getModel();
        
        if(listaRubro!=null  &&  !listaRubro.isEmpty()){
            for(Rubro rubro :  listaRubro ){
                model.addElement(rubro.getNombre());
            }
            comboRubro.setModel(model);
        }        
    }

    private void llenarSubRubros() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboSubRubro.getModel();
        try{
            listaSubRubro = new SubRubroService().getAllSubRubros();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se encuentran SubRubros para llenar");
        }
        if(listaSubRubro != null && !listaSubRubro.isEmpty()){
            for(SubRubro subRubro : listaSubRubro){
                model.addElement(subRubro.getDetalle());
            }
            comboSubRubro.setModel(model);
        }
    }

    private void limpiarCampos() {
        codigoTxt.setText("");
        codigoBarrasTxt.setText("");
        comboRubro.removeAllItems();
        comboRubro.addItem("");
        comboSubRubro.removeAllItems();
        comboSubRubro.addItem("");
        detalleTxt.setText("");
        precioTxt.setText("0.00");
        sugeridoTxt.setText("0.00");
        impuestoTxt.setText("0.00");
    }
}
