/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Producto;
import ar.com.gmeventas.services.ProductoService;
import static java.lang.Math.rint;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class MostrarTablaProductosACambiarPrecios extends javax.swing.JFrame {

    private Integer deCodigo;
    private Integer aCodigo;
    private Float porcentaje;
    private List<Producto> productos = null;
    /**
     * Creates new form MostrarTablaProductosACambiarPrecios
     */
    public MostrarTablaProductosACambiarPrecios(Integer deCodigo, Integer aCodigo, Float porce) {
        initComponents();
        this.deCodigo = deCodigo;
        this.aCodigo = aCodigo;
        porcentaje = porce;
        llenarTabla();
    }

    private MostrarTablaProductosACambiarPrecios() {
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        volverBtn = new javax.swing.JButton();
        sacarDeLaListaBtn = new javax.swing.JButton();
        grabarPreciosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Detalle", "Precio Actual", "Nuevo Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        sacarDeLaListaBtn.setText("Sacar de la Lista");

        grabarPreciosBtn.setText("Grabar");
        grabarPreciosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarPreciosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(grabarPreciosBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                        .addComponent(sacarDeLaListaBtn)
                        .addGap(347, 347, 347)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(sacarDeLaListaBtn)
                    .addComponent(grabarPreciosBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        PreciosEntreCodigosFrame pecf = new PreciosEntreCodigosFrame();
        pecf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void grabarPreciosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarPreciosBtnActionPerformed
        grabarPrecios();
    }//GEN-LAST:event_grabarPreciosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTablaProductosACambiarPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTablaProductosACambiarPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTablaProductosACambiarPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTablaProductosACambiarPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTablaProductosACambiarPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton grabarPreciosBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sacarDeLaListaBtn;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
        try {
            productos = new ProductoService().getProductosEntreCodigos(deCodigo, aCodigo);
        } catch (Exception ex) {
            Logger.getLogger(MostrarTablaProductosACambiarPrecios.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
        if (productos != null) {
            for (Producto prod:productos){
                //System.out.println(prod.getDetalle());
                Object linea[] = new Object[4];
                linea[0] = prod.getCodigo();
                linea[1] = prod.getDetalle();
                linea[2] = prod.getPrecio();
                Double precioConAumento = prod.getPrecio() * (1 + (porcentaje/100));
                linea[3] = rint(precioConAumento*100)/100;
                model.addRow(linea);
            }
            tablaProductos.setModel(model);
        }
    }

    private void grabarPrecios() {
        for (Producto prod: productos) {
            Double precioConAumento = prod.getPrecio() * (1 + (porcentaje/100));
            prod.setPrecio(rint(precioConAumento*100)/100);
            try {
                new ProductoService().updateProducto(prod);
            } catch (Exception ex) {
                Logger.getLogger(MostrarTablaProductosACambiarPrecios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(this, "Productos Actualizados");
        PreciosEntreCodigosFrame pecf = new PreciosEntreCodigosFrame();
        pecf.setVisible(true);
        this.dispose();
    }
}
