/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ar.com.gmeventas.frame;

import ar.com.gmeventas.entities.Producto;
import ar.com.gmeventas.entities.Rubro;
import ar.com.gmeventas.entities.SubRubro;
import ar.com.gmeventas.services.ProductoService;
import ar.com.gmeventas.services.RubroService;
import ar.com.gmeventas.services.SubRubroService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcela
 */
public class NuevoProductoFrame extends javax.swing.JFrame {

    private List<Rubro> listaRubros = new ArrayList<Rubro>();
    private List<SubRubro> listaSubRubros=new ArrayList<SubRubro>();
    private String filtro;
    /**
     * Creates new form NuevoProductoFrame
     */
    public NuevoProductoFrame() {
        this.initComponents();
        this.borrarCampos();
        this.llenarComboRubro();
        this.llenarComboSubRubro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        guardarBtn = new javax.swing.JButton();
        volerBtn = new javax.swing.JButton();
        idTxt = new javax.swing.JTextField();
        codigoBarrasTxt = new javax.swing.JTextField();
        impuestoTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        sugeridoTxt = new javax.swing.JTextField();
        precioTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboRubro = new javax.swing.JComboBox();
        comboSubRubro = new javax.swing.JComboBox();
        inactivoChk = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precioCostoTxt = new javax.swing.JTextField();
        impuestoCostoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO PRODUCTO");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        volerBtn.setText("Volver");
        volerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volerBtnActionPerformed(evt);
            }
        });

        idTxt.setText("CODIGO");
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        codigoBarrasTxt.setText("Codigo de Barras");
        codigoBarrasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasTxtActionPerformed(evt);
            }
        });

        impuestoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoTxt.setText("Impuesto");

        nombreTxt.setText("DETALLE");

        sugeridoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sugeridoTxt.setText("Sugerido");

        precioTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioTxt.setText("Precio");

        jLabel1.setText("Código");

        jLabel4.setText("Impuesto");

        jLabel5.setText("Detalle:");

        jLabel6.setText("Precio");

        jLabel7.setText("Sugerido");

        jLabel9.setText("Rubro:");

        jLabel10.setText("Sub Rubro:");

        comboRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRubroActionPerformed(evt);
            }
        });

        comboSubRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inactivoChk.setText("Inactivo");

        jLabel3.setText("Código de Barras:");

        jLabel8.setText("*");

        jLabel11.setText("*");

        jLabel12.setText("*");

        jLabel13.setText("*");

        jLabel14.setText("*");

        jLabel2.setText("Costos:");

        precioCostoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioCostoTxt.setText("P.COSTO");

        impuestoCostoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoCostoTxt.setText("I.COSTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guardarBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inactivoChk))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(precioCostoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboSubRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboRubro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(volerBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(impuestoTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(sugeridoTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(impuestoCostoTxt))))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(inactivoChk))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)
                            .addComponent(precioCostoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(impuestoCostoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sugeridoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboSubRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(volerBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volerBtnActionPerformed
        AbmProductoFrame abmProductoFrame = new AbmProductoFrame(filtro);
        abmProductoFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volerBtnActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void codigoBarrasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasTxtActionPerformed

    private void comboRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProductoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoBarrasTxt;
    private javax.swing.JComboBox comboRubro;
    private javax.swing.JComboBox comboSubRubro;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField impuestoCostoTxt;
    private javax.swing.JTextField impuestoTxt;
    private javax.swing.JCheckBox inactivoChk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField precioCostoTxt;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JTextField sugeridoTxt;
    private javax.swing.JButton volerBtn;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if(validarCampos()){
            Producto producto = new Producto();
            producto.setCodigo(Integer.valueOf(idTxt.getText()));
            producto.setDetalle(nombreTxt.getText());
            if (!codigoBarrasTxt.getText().isEmpty()){
                producto.setCodigoBarras(Long.valueOf(codigoBarrasTxt.getText()));
            }else{
                producto.setCodigoBarras(null);
            }
            if (!impuestoTxt.getText().isEmpty()){
                producto.setImpuesto(Float.valueOf(impuestoTxt.getText().replace(",", ".")));
            }else{
                producto.setImpuesto(Float.valueOf("0.00"));
            }
            if (!sugeridoTxt.getText().isEmpty()){
                producto.setSugerido(Double.valueOf(sugeridoTxt.getText().replace(",", ".")));
            }else{
                producto.setSugerido(Double.valueOf("0.00"));
            }
            producto.setPrecio(Double.valueOf(precioTxt.getText().replace(",", ".")));
            if (inactivoChk.isSelected()){
                producto.setInactivo(true);
            }else{
                producto.setInactivo(false);
            }
            if(precioCostoTxt.getText().isEmpty()){
                producto.setCostoP(0.00);
            }else{
                Double pc = Double.valueOf(precioCostoTxt.getText().replace(",", "."));
                producto.setCostoP(pc);
            }
            if(impuestoCostoTxt.getText().isEmpty()){
                producto.setCostoI(0.00);
            }else{
                Double ic = Double.valueOf(impuestoCostoTxt.getText().replace(",", "."));
                producto.setCostoI(ic);
            }
            if (asignarRubro(producto)){
                if (asignarSubRubro(producto)){
                    try{
                        new ProductoService().guardarProducto(producto);
                        JOptionPane.showMessageDialog(this, "Producto guardado correctamente.");
                    }catch(Exception ex){   
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error guardando el Producto.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error (Sub Rubro) guardando el Producto.");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error (Rubro) guardando el Producto.");
            }
            borrarCampos();
            llenarComboRubro();
            llenarComboSubRubro();
        }
    }

    private void borrarCampos() {
        comboRubro.removeAllItems();
        comboRubro.addItem(" ");
        comboSubRubro.removeAllItems();
        comboSubRubro.addItem(" ");
        idTxt.setText("");
        codigoBarrasTxt.setText("");
        impuestoTxt.setText("");
        sugeridoTxt.setText("");
        precioTxt.setText("");
        precioCostoTxt.setText("");
        impuestoCostoTxt.setText("");
        nombreTxt.setText("");
        inactivoChk.setSelected(false);
    }

    private void llenarComboRubro()  {
        
        try{
            listaRubros = new RubroService().getAllRubros();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se encuentran Rubros para llenar");
        }
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboRubro.getModel();
        
        if(listaRubros!=null  &&  !listaRubros.isEmpty()){
            for(Rubro rubro :  listaRubros ){
                model.addElement(rubro.getNombre());
            }
            comboRubro.setModel(model);
        }
    }

    private void llenarComboSubRubro() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboSubRubro.getModel();
        try{
            listaSubRubros = new SubRubroService().getAllSubRubros();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se encuentran SubRubros para llenar");
        }
        if(listaSubRubros != null && !listaSubRubros.isEmpty()){
            for(SubRubro subRubro : listaSubRubros){
                model.addElement(subRubro.getDetalle());
            }
            comboSubRubro.setModel(model);
        }
    }

    private boolean validarCampos() {
        if (nombreTxt.getText().trim().length() > 34) {
            JOptionPane.showMessageDialog(this, "Largo Producto Superado - " + String.valueOf(nombreTxt.getText().trim().length()));
            return false;
        }
        if(idTxt.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Producto - Falta completar CODIGO");
            return false;
        }
        if (nombreTxt.getText().trim().length()==0) {
            JOptionPane.showMessageDialog(this, "Producto - Falta completar NOMBRE");
            return false;
        }
        if (precioTxt.getText().trim().length()==0) {
            JOptionPane.showMessageDialog(this, "Producto - No permitido Sin precio");
            return false;
        }
        if(comboRubro.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Producto - Seleccione Rubro");
            return false;
        }
        if(comboSubRubro.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "producto - Seleccione Sub Rubro");
            return false;
        }
     return true;   
    }

    private boolean asignarRubro(Producto prod) {
        int itemSeleccionado = comboRubro.getSelectedIndex();
        if(itemSeleccionado >= 1){
            prod.setRubro(listaRubros.get(itemSeleccionado-1));
            return true;
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Rubro de la lista.");
            return false;
        }
    }

    private boolean asignarSubRubro(Producto prod) {
        int itemSeleccionado = comboSubRubro.getSelectedIndex();
        if(itemSeleccionado >= 1){
            prod.setSubRubro(listaSubRubros.get(itemSeleccionado-1));
            return true;
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un SubRubro de la lista.");
            return false;
        }
    }
}